name: Release Artifacts (main)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: ./.github/workflows/_shared-build.yml
    with:
      publish: true
    secrets: inherit
